spark_config_a:
    #spark_master: "local[*]" # drop line
    spark.executor.memory: "16g"
    spark.executor.memoryOverhead: "2g"
    spark.executor.cores: 3
    spark.task.cpus: 3
    spark.driver.memory: "16g"
    spark.rpc.message.maxSize: 512
    spark.driver.maxResultSize : "2g"
    spark.sql.adaptive.enabled: "false"
    spark.dynamicAllocation.enabled: "false"
    spark.dynamicAllocation.initialExecutors: 1
    spark.dynamicAllocation.maxExecutors: 4
    spark.dynamicAllocation.minExecutors: 0
    spark.dynamicAllocation.shuffleTracking.enabled: "true"
    spark.sql.hive.metastorePartitionPruningFallbackOnException: "true"
    
spark_config_b:
    spark.executor.memory: "9g"
    spark.executor.memoryOverhead: "2g"
    spark.executor.cores: 3
    spark.task.cpus: 3
    spark.driver.memory: "9g"
    spark.rpc.message.maxSize: 512
    spark.driver.maxResultSize : "2g"
    spark.sql.adaptive.enabled: "false"
    spark.dynamicAllocation.enabled: "true"
    spark.dynamicAllocation.initialExecutors: 1
    spark.dynamicAllocation.maxExecutors: 4
    spark.dynamicAllocation.minExecutors: 0
    spark.dynamicAllocation.shuffleTracking.enabled: "true"
    spark.sql.hive.metastorePartitionPruningFallbackOnException: "true"
